"""
Auto-generated by ToolForge
Tool: config_manager
ID: cd522c2f-77f1-450d-a837-48ed14014b18
Date: 2026-02-13T07:21:33.057594
Security Level: NORMAL
Status: STAGED (pending Guardian audit)
"""

def config_manager(config_file, changes=None):
    import json
    with open(config_file, 'r') as file:
        config = json.load(file)
    if changes is not None:
        config.update(changes)
    with open(config_file, 'w') as file:
        json.dump(config, file, indent=4)
    print(f'Configuration updated in {config_file}')