"""
Auto-generated by ToolForge
Tool: check_memory_usage
ID: 74eeee60-7768-4c48-812d-f2dd0492e898
Date: 2026-02-19T12:51:48.886417
Security Level: NORMAL
Status: STAGED (pending Guardian audit)
"""

def check_memory_usage():
    import psutil
    memory = psutil.virtual_memory()
    return {'total': memory.total, 'available': memory.available, 'percent': memory.percent, 'used': memory.used, 'free': memory.free}