"""
Auto-generated by ToolForge
Tool: code_optimizer
ID: 923f215e-035b-4fdd-9760-c5eec81036a4
Date: 2026-02-18T19:53:18.661499
Security Level: NORMAL
Status: STAGED (pending Guardian audit)
"""

def code_optimizer(source_code):
    # 检测源代码中的重复部分
    duplicates = detect_duplicates(source_code)
    if duplicates:
        # 提供改进建议
        optimized_code = optimize_duplicates(duplicates)
        return optimized_code
    else:
        return source_code